#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BuscaPreco_Android.Resource", IsApplication=true)]

namespace BuscaPreco_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::BuscaPreco_Android.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::BuscaPreco_Android.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::BuscaPreco_Android.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int barcode_128x128 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int barcode_64x64 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_logar_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int color = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int edit_text_detalhe_produto_style = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int edit_text_style = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int engrenagem_configurar_32x32 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Intellis = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int lupa_verde_128x128 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int lupa_verde_borda_redonda_64x64 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int produto_caixa_48x48 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ProgressBarStyle = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int sincronizar_48x48 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int textView_border_listView = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int usuario_48x48 = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int btnAreaDeTrabalho_ListagemProdutos = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int btnAreaDeTrabalho_SincronizarProdutos = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int btnAreaDeTrabalho_SincronizarUsuarios = 2131165186;
			
			// aapt resource value: 0x7f07000d
			public const int btnConfig_Salvar = 2131165197;
			
			// aapt resource value: 0x7f07003f
			public const int btnListagemProduto_BiparCodigo = 2131165247;
			
			// aapt resource value: 0x7f070035
			public const int btnLogin = 2131165237;
			
			// aapt resource value: 0x7f07003a
			public const int btnMain_Config = 2131165242;
			
			// aapt resource value: 0x7f070041
			public const int btnSincronizarProduto_Sincronizar = 2131165249;
			
			// aapt resource value: 0x7f070044
			public const int contentFrame = 2131165252;
			
			// aapt resource value: 0x7f07002a
			public const int d_inferior = 2131165226;
			
			// aapt resource value: 0x7f070028
			public const int d_superior = 2131165224;
			
			// aapt resource value: 0x7f070027
			public const int direita = 2131165223;
			
			// aapt resource value: 0x7f070025
			public const int e_inferior = 2131165221;
			
			// aapt resource value: 0x7f070023
			public const int e_superior = 2131165219;
			
			// aapt resource value: 0x7f070007
			public const int edConfig_IP = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int edConfig_NomeDB = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int edConfig_Porta = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int edConfig_Senha = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int edConfig_Usuario = 2131165194;
			
			// aapt resource value: 0x7f07000f
			public const int edDetalheProduto_CodigoBarra = 2131165199;
			
			// aapt resource value: 0x7f07001b
			public const int edDetalheProduto_Estoque = 2131165211;
			
			// aapt resource value: 0x7f070013
			public const int edDetalheProduto_NomeProduto = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int edDetalheProduto_ValorCusto = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int edDetalheProduto_ValorVenda = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int edDetalheProduto_ValorVendaPrazo = 2131165210;
			
			// aapt resource value: 0x7f07001d
			public const int edDetalheProduto_departamento = 2131165213;
			
			// aapt resource value: 0x7f07001f
			public const int edDetalheProduto_fornecedor = 2131165215;
			
			// aapt resource value: 0x7f070011
			public const int edDetalheProduto_referencia = 2131165201;
			
			// aapt resource value: 0x7f07003c
			public const int edListaProduto_Pesquisa = 2131165244;
			
			// aapt resource value: 0x7f070033
			public const int edLogin_Senha = 2131165235;
			
			// aapt resource value: 0x7f070032
			public const int edLogin_Usuario = 2131165234;
			
			// aapt resource value: 0x7f070022
			public const int esquerda = 2131165218;
			
			// aapt resource value: 0x7f07003e
			public const int imgBtnListagemProduto_Pesquisar = 2131165246;
			
			// aapt resource value: 0x7f070019
			public const int layDetalheProduto_ = 2131165209;
			
			// aapt resource value: 0x7f07000e
			public const int layDetalheProduto_codigoBarra = 2131165198;
			
			// aapt resource value: 0x7f07001c
			public const int layDetalheProduto_departamento = 2131165212;
			
			// aapt resource value: 0x7f07001e
			public const int layDetalheProduto_fornecedor = 2131165214;
			
			// aapt resource value: 0x7f070012
			public const int layDetalheProduto_nome = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int layDetalheProduto_precoCusto = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int layDetalheProduto_precoCustoVenda = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int layDetalheProduto_precoVenda = 2131165207;
			
			// aapt resource value: 0x7f070031
			public const int lay_main_loginSenha = 2131165233;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout1 = 2131165187;
			
			// aapt resource value: 0x7f07002f
			public const int linearLayout10 = 2131165231;
			
			// aapt resource value: 0x7f07002e
			public const int linearLayout11 = 2131165230;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout2 = 2131165189;
			
			// aapt resource value: 0x7f070010
			public const int linearLayout3 = 2131165200;
			
			// aapt resource value: 0x7f070037
			public const int linearLayout4 = 2131165239;
			
			// aapt resource value: 0x7f070039
			public const int linearLayout5 = 2131165241;
			
			// aapt resource value: 0x7f070034
			public const int linearLayout6 = 2131165236;
			
			// aapt resource value: 0x7f07002d
			public const int linearLayout8 = 2131165229;
			
			// aapt resource value: 0x7f07002c
			public const int linearLayout9 = 2131165228;
			
			// aapt resource value: 0x7f07003d
			public const int linearLayoutListagemProdutos_Botoes = 2131165245;
			
			// aapt resource value: 0x7f07003b
			public const int linearLayoutPsqProduto = 2131165243;
			
			// aapt resource value: 0x7f070020
			public const int linha = 2131165216;
			
			// aapt resource value: 0x7f070040
			public const int lstView_Produto_Listagem = 2131165248;
			
			// aapt resource value: 0x7f070036
			public const int pgbLogin_Progresso = 2131165238;
			
			// aapt resource value: 0x7f070043
			public const int pgbSincronizarProduto_Status = 2131165251;
			
			// aapt resource value: 0x7f07000c
			public const int relativeLayout1 = 2131165196;
			
			// aapt resource value: 0x7f070038
			public const int switchMain_AcessoOffline = 2131165240;
			
			// aapt resource value: 0x7f070004
			public const int textView1 = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int textView2 = 2131165190;
			
			// aapt resource value: 0x7f070026
			public const int txtListagemProduto_Nome = 2131165222;
			
			// aapt resource value: 0x7f070021
			public const int txtListagemProduto_UkCodigo = 2131165217;
			
			// aapt resource value: 0x7f070029
			public const int txtListagemProduto_ValorDeCusto = 2131165225;
			
			// aapt resource value: 0x7f07002b
			public const int txtListagemProduto_ValorDeVenda = 2131165227;
			
			// aapt resource value: 0x7f070024
			public const int txtListagemProdutos_CodigoBarra = 2131165220;
			
			// aapt resource value: 0x7f070030
			public const int txtLogin_FazerLogin = 2131165232;
			
			// aapt resource value: 0x7f070042
			public const int txtSincronizarProduto_Aviso1 = 2131165250;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AreaDeTrabalho = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ConfiguracaoAcessoInicial = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Dialog_DetalheProduto = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListView_ListagemProduto_Row = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Produto_Listagem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SincronizarProduto = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int zxingscanneractivitylayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int zxingscannerfragmentlayout = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
